variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Xmx3g"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-fast --show-version"

image: maven:3-openjdk-11-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

before_script:
  - free -mh

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

verify:jdk11:
  stage: build
  script:
    - 'cd Server'
    - 'mvn $MAVEN_CLI_OPTS verify -DskipTests'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:json:
  stage: test
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends jq
    - 'find . -name \*.json -type f -print0 | xargs -0 -n1 -P8 jq empty'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
